# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 迁出代码
      - uses: actions/checkout@v2

      # 安装依赖并打包
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"

      - name: Build Project
        run: |
          npm install
          npm run build

      - name: List output files
        run: ls -a dist # 显示生成的目录文件

      # 上传到服务器
      # - name: FTP-Deploy-Action
      #   uses: SamKirkland/FTP-Deploy-Action@3.1.0
      #   with:
      #     ftp-server: ftp://47.105.126.118/
      #     ftp-username: ftp
      #     ftp-password: ${{ secrets.FTP_PASSWORD }}
      #     local-dir: dist # This folder is NOT going to upload by default unless you add it to .git-ftp-include

      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: "ftp://47.105.126.118/"
          user: "ftp"
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: "dist"
          remoteDir: "vue-study"
